// ============================================
// Vercel Serverless Function: /api/gemini
// Handles Gemini AI requests server-side.
// Reads GEMINI_API_KEY from environment variables.
// Key is NEVER exposed to the frontend browser.
// ============================================

export default async function handler(req, res) {
  // Set CORS headers for security and flexibility
  res.setHeader('Access-Control-Allow-Credentials', 'true');
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS,PATCH,DELETE,POST,PUT');
  res.setHeader(
    'Access-Control-Allow-Headers',
    'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version'
  );

  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed. Only POST requests are supported.' });
  }

  // 1. Read API key from server environment
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey || !apiKey.trim()) {
    console.error('[/api/gemini] GEMINI_API_KEY environment variable is not set in Vercel.');
    return res.status(500).json({
      error: 'Gemini API key is not configured on the server. Please add GEMINI_API_KEY to your Vercel Environment Variables.'
    });
  }

  try {
    const { prompt, generationConfig } = req.body || {};

    if (!prompt || typeof prompt !== 'string' || !prompt.trim()) {
      return res.status(400).json({ error: 'Missing or empty "prompt" parameter in request body.' });
    }

    // Server strictly calls gemini-3.6-flash
    const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/gemini-3.6-flash:generateContent?key=${apiKey.trim()}`;

    const payload = {
      contents: [{ parts: [{ text: prompt }] }],
      generationConfig: {
        temperature: generationConfig?.temperature ?? 0.2,
        maxOutputTokens: generationConfig?.maxOutputTokens ?? 2048,
        responseMimeType: generationConfig?.responseMimeType ?? 'application/json'
      }
    };

    console.log(`[/api/gemini] Forwarding prompt to model "gemini-3.6-flash" (prompt length: ${prompt.length} chars)`);

    const googleResponse = await fetch(endpoint, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload)
    });

    if (!googleResponse.ok) {
      const errData = await googleResponse.json().catch(() => ({}));
      console.error(`[/api/gemini] Google API error (${googleResponse.status}):`, errData);
      
      const errorMessage = errData.error?.message || `Google Gemini API returned status ${googleResponse.status}`;
      return res.status(googleResponse.status).json({
        error: `AI Service error: ${errorMessage}`
      });
    }

    const data = await googleResponse.json();
    const rawText = data.candidates?.[0]?.content?.parts?.[0]?.text || '';

    if (!rawText) {
      console.warn('[/api/gemini] Google response had no text candidate:', JSON.stringify(data));
      return res.status(502).json({
        error: 'No text was generated by the AI model. Please try again with a clearer pitch.'
      });
    }

    return res.status(200).json({
      text: rawText,
      model: 'gemini-3.6-flash',
      usage: data.usageMetadata || null
    });

  } catch (err) {
    console.error('[/api/gemini] Unexpected server error:', err);
    return res.status(500).json({
      error: `Server internal error: ${err.message || 'Unknown error occurred'}`
    });
  }
}
